### ISSUE TITLE
SyntaxError running run.py

### ISSUE THREAD

**Issue by aaa-bbb-ccc** [ecthros/uncaptcha2#12]
Hey, im starting with coding so i don't know much why it fails.
I've installed all the dependences needed running _pip install -r dependences.txt_ and when i run the _run.py_ code i get this:

> Traceback (most recent call last):
  File "run.py", line 2, in <module>
    import pyautogui
  File "/home/albert/.local/lib/python2.7/site-packages/pyautogui/__init__.py", line 84, in <module>
    import pyscreeze
  File "/home/albert/.local/lib/python2.7/site-packages/pyscreeze/__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator

**Comment by aaa-bbb-ccc** [comment]
Okay, was running in python2
